### ISSUE TITLE
Προσθήκη κανόνα

### ISSUE THREAD

**Issue by jtsagata** [ubuntu-gr/facebook-group#5]
10. Αν σε μια δημοσιεύση υπάρχουν απαντήσεις, τότε αυτή μπορεί να διαγραφεί μόνον απο τους διαχειρηστές σε περίπτωση παραβίασης των κανονισμών. Σε καμία περίπτωση δεν θα διαγράφετε απο τον χρήστη που την ανάρτησε. 

Μιας και πολοι χρήστες διαγράφουν την ερώτηση μετά που θα λάβουν απάντηση.

**Comment by NikTh** [comment]
Πολύ αυταρχικός μου φαίνεται ο συγκεκριμένος κανόνας, για ένα θέμα που την ευθύνη έχουν οι Original Posters. Δικό τους είναι το ποστ άλλωστε, ότι θέλουν το κάνουν. 
Ωστόσο, μπορούμε να αλλάξουμε λίγο τη σύνταξη και να το κάνουμε πχ

10. Οι δημοσιεύσεις στο γκρουπ της κοινότητας διατηρούνται ως βάση δεδομένων επίλυσης παρόμοιων προβλημάτων τα οποία ενδεχομένως να έχουν άλλοι χρήστες. Γι' αυτό το λόγο οι δημοσιεύσεις είναι καλό να μη διαγράφονται, ούτε από τον δημιουργό της δημοσίευσης. Σε αντίθετη περίπτωση οι εκάστοτε διαχειριστές της κοινότητας διατηρούν το δικαίωμα να διαγράψουν τον χρήστη από το γκρουπ, προσωρινά ή μόνιμα.

**Comment by iosifidis** [comment]
Συμφωνώ με το Νίκο. 
Επίσης να διατυπωθεί ότι το προσωρινά αφορά αν το κάνει μια φορά ενώ το μόνιμα εάν το κάνει επανειλημμένα.

**Comment by jtsagata** [comment]
> Γι' αυτό το λόγο οι δημοσιεύσεις <del>είναι καλό να μη </del>**δεν θα πρέπει να** διαγράφονται, <del>ούτε</del> από τον δημιουργό της δημοσίευσης.

**Comment by NikTh** [comment]
Δεν βλέπω συμμετοχή από άλλους όμως.

**Comment by irenegr** [comment]
+1 στον Νίκο.

**Comment by cerebrux** [comment]
+1

PS. Μπράβο στον @jtsagata

**Comment by NikTh** [comment]
> Οι δημοσιεύσεις στο γκρουπ της κοινότητας διατηρούνται ως βάση δεδομένων επίλυσης παρόμοιων προβλημάτων τα οποία ενδεχομένως να έχουν άλλοι χρήστες. Γι' αυτό το λόγο οι δημοσιεύσεις δεν πρέπει να διαγράφονται από τον δημιουργό της δημοσίευσης. 
> Σε αντίθετη περίπτωση οι εκάστοτε διαχειριστές της κοινότητας διατηρούν το δικαίωμα να διαγράψουν τον χρήστη από το γκρουπ, προσωρινά (πχ εάν το κάνει μια φορά) ή μόνιμα (πχ εάν το κάνει επανειλημμένα), χωρίς προειδοποίηση!

Εάν είμαστε εντάξει με το παραπάνω; αν ναι να το συγχωνεύσω στους κανόνες. Ένα :thumbsup: σε αυτό το comment φτάνει. 

@iosifidis @irenegr @cerebrux

**Comment by irenegr** [comment]
+1

**Comment by iosifidis** [comment]
+1

**Comment by NikTh** [comment]
https://github.com/ubuntu-gr/facebook-group/blob/master/README.md
